# Generated by Django 4.0.4 on 2022-04-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
    ]
